on:
  push:
    branches:
      - master
jobs:
  build-container:
    runs-on: container-builder
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the master branch
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Build container image
        run: |
          echo "Setting up registry variables..."
          REGISTRY_HOST=$(echo "${{ forgejo.server_url }}" | cut -d'/' -f3)
          IMAGE_IDENTITY=${REGISTRY_HOST}/${{ forgejo.repository }}
          ACTOR="${{ forgejo.actor }}"
          
          echo "Logging into $REGISTRY_HOST..."
          echo "${{ REGISTRY_TOKEN }}" | podman login ${REGISTRY_HOST} -u ${ACTOR,,} --password-stdin

          echo "Building container image..."
          podman build -t "${IMAGE_IDENTITY,,}:latest" .

          echo "Pushing container image..."
          podman push "${IMAGE_IDENTITY,,}:latest"
